
version: "3.9"
services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MODEL_DIR=/app/model
      - SPARK_MASTER=local[*]
    ports:
      - "8501:8501"
    volumes:
      - ./model:/app/model
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - MODEL_DIR=/app/model
      - SPARK_MASTER=local[*]
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
